version: '3.8'

services:
  money_mate_server:
    build:
      context: .
      target: development-build-stage
    container_name: money_mate_server
    ports:
      - '1511:1511'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env.development.local
    environment:
      - DB_HOST=172.21.0.2
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=money_mate
    networks:
      - backend
    depends_on:
      - money_mate_db
  money_mate_db:
    image: postgres:14.1-alpine
    container_name: money_mate_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=money_mate
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
    driver: local
